// Package verdict.v1 defines the Twirp service surface for Verdict.
//
// Model documents, input payloads, outputs and traces cross the wire as
// JSON-encoded strings rather than being re-modelled in protobuf. There is one
// source of truth for each of those shapes — DMN XML and the VDJ schema for
// models, `pkg/trace` for traces — and re-modelling them here would guarantee
// drift between the wire and the library on the first schema change.
//
// What *is* modelled in protobuf is the RPC envelope: which model, which
// decision, which version, and the diagnostics that come back. Those are
// Verdict's own vocabulary and are stable.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: server/twirp/service.proto

package twirp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Severity ranks a diagnostic.
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_INFO        Severity = 1
	Severity_SEVERITY_WARNING     Severity = 2
	Severity_SEVERITY_ERROR       Severity = 3
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_INFO",
		2: "SEVERITY_WARNING",
		3: "SEVERITY_ERROR",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_INFO":        1,
		"SEVERITY_WARNING":     2,
		"SEVERITY_ERROR":       3,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_server_twirp_service_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_server_twirp_service_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_server_twirp_service_proto_rawDescGZIP(), []int{0}
}

// Diagnostic is one reported problem, anchored to a model element.
type Diagnostic struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Code        string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Severity    Severity               `protobuf:"varint,2,opt,name=severity,proto3,enum=verdict.v1.Severity" json:"severity,omitempty"`
	Message     string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ModelId     string                 `protobuf:"bytes,4,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ElementId   string                 `protobuf:"bytes,5,opt,name=element_id,json=elementId,proto3" json:"element_id,omitempty"`
	ElementName string                 `protobuf:"bytes,6,opt,name=element_name,json=elementName,proto3" json:"element_name,omitempty"`
	// detail_json carries code-specific structured context as a JSON object.
	DetailJson    string `protobuf:"bytes,7,opt,name=detail_json,json=detailJson,proto3" json:"detail_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_server_twirp_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_server_twirp_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_server_twirp_service_proto_rawDescGZIP(), []int{0}
}

func (x *Diagnostic) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Diagnostic) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Diagnostic) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *Diagnostic) GetElementId() string {
	if x != nil {
		return x.ElementId
	}
	return ""
}

func (x *Diagnostic) GetElementName() string {
	if x != nil {
		return x.ElementName
	}
	return ""
}

func (x *Diagnostic) GetDetailJson() string {
	if x != nil {
		return x.DetailJson
	}
	return ""
}

// Model identifies a registered model.
type Model struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// hash is the content address of the source document. Loading the same
	// content twice is idempotent and returns the same hash.
	Hash string `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	// decision_ids and service_ids let a caller discover what it can evaluate
	// without fetching the whole document.
	DecisionIds         []string      `protobuf:"bytes,5,rep,name=decision_ids,json=decisionIds,proto3" json:"decision_ids,omitempty"`
	ServiceIds          []string      `protobuf:"bytes,6,rep,name=service_ids,json=serviceIds,proto3" json:"service_ids,omitempty"`
	TopLevelDecisionIds []string      `protobuf:"bytes,7,rep,name=top_level_decision_ids,json=topLevelDecisionIds,proto3" json:"top_level_decision_ids,omitempty"`
	Diagnostics         []*Diagnostic `protobuf:"bytes,8,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_server_twirp_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_server_twirp_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_server_twirp_service_proto_rawDescGZIP(), []int{1}
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Model) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Model) GetDecisionIds() []string {
	if x != nil {
		return x.DecisionIds
	}
	return nil
}

func (x *Model) GetServiceIds() []string {
	if x != nil {
		return x.ServiceIds
	}
	return nil
}

func (x *Model) GetTopLevelDecisionIds() []string {
	if x != nil {
		return x.TopLevelDecisionIds
	}
	return nil
}

func (x *Model) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type LoadModelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// source is the model document: DMN XML or Verdict Decision JSON. The format
	// is detected from the content.
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// path loads from a file on the server instead of from source. Only honoured
	// when the server was started with a model root.
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelRequest) Reset() {
	*x = LoadModelRequest{}
	mi := &file_server_twirp_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelRequest) ProtoMessage() {}

func (x *LoadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_twirp_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelRequest.ProtoReflect.Descriptor instead.
func (*LoadModelRequest) Descriptor() ([]byte, []int) {
	return file_server_twirp_service_proto_rawDescGZIP(), []int{2}
}

func (x *LoadModelRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LoadModelRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type LoadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *Model                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelResponse) Reset() {
	*x = LoadModelResponse{}
	mi := &file_server_twirp_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelResponse) ProtoMessage() {}

func (x *LoadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_twirp_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelResponse.ProtoReflect.Descriptor instead.
func (*LoadModelResponse) Descriptor() ([]byte, []int) {
	return file_server_twirp_service_proto_rawDescGZIP(), []int{3}
}

func (x *LoadModelResponse) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_server_twirp_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_twirp_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_server_twirp_service_proto_rawDescGZIP(), []int{4}
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_server_twirp_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_twirp_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_server_twirp_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListModelsResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

// EvaluateRequest runs a model's top-level decisions.
type EvaluateRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ModelId string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// version pins a loaded version. Empty means the most recently loaded.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// inputs_json is a JSON object of input-data values.
	InputsJson string `protobuf:"bytes,3,opt,name=inputs_json,json=inputsJson,proto3" json:"inputs_json,omitempty"`
	// include_trace returns the execution trace inline. The trace is always
	// recorded when the server's tracing is on; this controls whether it is
	// returned rather than only retained.
	IncludeTrace  bool `protobuf:"varint,4,opt,name=include_trace,json=includeTrace,proto3" json:"include_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_server_twirp_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_twirp_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_server_twirp_service_proto_rawDescGZIP(), []int{6}
}

func (x *EvaluateRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *EvaluateRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EvaluateRequest) GetInputsJson() string {
	if x != nil {
		return x.InputsJson
	}
	return ""
}

func (x *EvaluateRequest) GetIncludeTrace() bool {
	if x != nil {
		return x.IncludeTrace
	}
	return false
}

type EvaluateDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	DecisionId    string                 `protobuf:"bytes,3,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	InputsJson    string                 `protobuf:"bytes,4,opt,name=inputs_json,json=inputsJson,proto3" json:"inputs_json,omitempty"`
	IncludeTrace  bool                   `protobuf:"varint,5,opt,name=include_trace,json=includeTrace,proto3" json:"include_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateDecisionRequest) Reset() {
	*x = EvaluateDecisionRequest{}
	mi := &file_server_twirp_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateDecisionRequest) ProtoMessage() {}

func (x *EvaluateDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_twirp_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateDecisionRequest.ProtoReflect.Descriptor instead.
func (*EvaluateDecisionRequest) Descriptor() ([]byte, []int) {
	return file_server_twirp_service_proto_rawDescGZIP(), []int{7}
}

func (x *EvaluateDecisionRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *EvaluateDecisionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EvaluateDecisionRequest) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *EvaluateDecisionRequest) GetInputsJson() string {
	if x != nil {
		return x.InputsJson
	}
	return ""
}

func (x *EvaluateDecisionRequest) GetIncludeTrace() bool {
	if x != nil {
		return x.IncludeTrace
	}
	return false
}

type EvaluateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ServiceId     string                 `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	InputsJson    string                 `protobuf:"bytes,4,opt,name=inputs_json,json=inputsJson,proto3" json:"inputs_json,omitempty"`
	IncludeTrace  bool                   `protobuf:"varint,5,opt,name=include_trace,json=includeTrace,proto3" json:"include_trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateServiceRequest) Reset() {
	*x = EvaluateServiceRequest{}
	mi := &file_server_twirp_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateServiceRequest) ProtoMessage() {}

func (x *EvaluateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_twirp_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateServiceRequest.ProtoReflect.Descriptor instead.
func (*EvaluateServiceRequest) Descriptor() ([]byte, []int) {
	return file_server_twirp_service_proto_rawDescGZIP(), []int{8}
}

func (x *EvaluateServiceRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *EvaluateServiceRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EvaluateServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *EvaluateServiceRequest) GetInputsJson() string {
	if x != nil {
		return x.InputsJson
	}
	return ""
}

func (x *EvaluateServiceRequest) GetIncludeTrace() bool {
	if x != nil {
		return x.IncludeTrace
	}
	return false
}

type EvaluateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// outputs_json is a JSON object of the evaluated decisions' values.
	OutputsJson string `protobuf:"bytes,1,opt,name=outputs_json,json=outputsJson,proto3" json:"outputs_json,omitempty"`
	// trace_id addresses the retained trace, for a later GetTrace.
	TraceId string `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// trace_json is the execution trace, present when include_trace was set.
	TraceJson     string        `protobuf:"bytes,3,opt,name=trace_json,json=traceJson,proto3" json:"trace_json,omitempty"`
	Diagnostics   []*Diagnostic `protobuf:"bytes,4,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	DurationNs    int64         `protobuf:"varint,5,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_server_twirp_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_twirp_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_server_twirp_service_proto_rawDescGZIP(), []int{9}
}

func (x *EvaluateResponse) GetOutputsJson() string {
	if x != nil {
		return x.OutputsJson
	}
	return ""
}

func (x *EvaluateResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *EvaluateResponse) GetTraceJson() string {
	if x != nil {
		return x.TraceJson
	}
	return ""
}

func (x *EvaluateResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *EvaluateResponse) GetDurationNs() int64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

type GetTraceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceRequest) Reset() {
	*x = GetTraceRequest{}
	mi := &file_server_twirp_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceRequest) ProtoMessage() {}

func (x *GetTraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_twirp_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceRequest.ProtoReflect.Descriptor instead.
func (*GetTraceRequest) Descriptor() ([]byte, []int) {
	return file_server_twirp_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetTraceRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type GetTraceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceJson     string                 `protobuf:"bytes,1,opt,name=trace_json,json=traceJson,proto3" json:"trace_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceResponse) Reset() {
	*x = GetTraceResponse{}
	mi := &file_server_twirp_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceResponse) ProtoMessage() {}

func (x *GetTraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_twirp_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceResponse.ProtoReflect.Descriptor instead.
func (*GetTraceResponse) Descriptor() ([]byte, []int) {
	return file_server_twirp_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetTraceResponse) GetTraceJson() string {
	if x != nil {
		return x.TraceJson
	}
	return ""
}

type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_server_twirp_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_twirp_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_server_twirp_service_proto_rawDescGZIP(), []int{12}
}

func (x *AnalyzeRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *AnalyzeRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type AnalyzeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// report_json is the full analysis report.
	ReportJson    string        `protobuf:"bytes,1,opt,name=report_json,json=reportJson,proto3" json:"report_json,omitempty"`
	Diagnostics   []*Diagnostic `protobuf:"bytes,2,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_server_twirp_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_twirp_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_server_twirp_service_proto_rawDescGZIP(), []int{13}
}

func (x *AnalyzeResponse) GetReportJson() string {
	if x != nil {
		return x.ReportJson
	}
	return ""
}

func (x *AnalyzeResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type ExplainRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ModelId string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// decision_id names the decision to explain. Empty lists the model's
	// decisions and services instead.
	DecisionId    string `protobuf:"bytes,3,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainRequest) Reset() {
	*x = ExplainRequest{}
	mi := &file_server_twirp_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainRequest) ProtoMessage() {}

func (x *ExplainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_twirp_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainRequest.ProtoReflect.Descriptor instead.
func (*ExplainRequest) Descriptor() ([]byte, []int) {
	return file_server_twirp_service_proto_rawDescGZIP(), []int{14}
}

func (x *ExplainRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ExplainRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ExplainRequest) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

type ExplainResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// slice_json is the structured explanation.
	SliceJson string `protobuf:"bytes,1,opt,name=slice_json,json=sliceJson,proto3" json:"slice_json,omitempty"`
	// text is the same explanation rendered as prose, which is what an agent
	// reading this over MCP actually wants.
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainResponse) Reset() {
	*x = ExplainResponse{}
	mi := &file_server_twirp_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainResponse) ProtoMessage() {}

func (x *ExplainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_twirp_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainResponse.ProtoReflect.Descriptor instead.
func (*ExplainResponse) Descriptor() ([]byte, []int) {
	return file_server_twirp_service_proto_rawDescGZIP(), []int{15}
}

func (x *ExplainResponse) GetSliceJson() string {
	if x != nil {
		return x.SliceJson
	}
	return ""
}

func (x *ExplainResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_server_twirp_service_proto protoreflect.FileDescriptor

const file_server_twirp_service_proto_rawDesc = "" +
	"\n" +
	"\x1aserver/twirp/service.proto\x12\n" +
	"verdict.v1\"\xea\x01\n" +
	"\n" +
	"Diagnostic\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x120\n" +
	"\bseverity\x18\x02 \x01(\x0e2\x14.verdict.v1.SeverityR\bseverity\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x19\n" +
	"\bmodel_id\x18\x04 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"element_id\x18\x05 \x01(\tR\telementId\x12!\n" +
	"\felement_name\x18\x06 \x01(\tR\velementName\x12\x1f\n" +
	"\vdetail_json\x18\a \x01(\tR\n" +
	"detailJson\"\x8c\x02\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\x12!\n" +
	"\fdecision_ids\x18\x05 \x03(\tR\vdecisionIds\x12\x1f\n" +
	"\vservice_ids\x18\x06 \x03(\tR\n" +
	"serviceIds\x123\n" +
	"\x16top_level_decision_ids\x18\a \x03(\tR\x13topLevelDecisionIds\x128\n" +
	"\vdiagnostics\x18\b \x03(\v2\x16.verdict.v1.DiagnosticR\vdiagnostics\">\n" +
	"\x10LoadModelRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"<\n" +
	"\x11LoadModelResponse\x12'\n" +
	"\x05model\x18\x01 \x01(\v2\x11.verdict.v1.ModelR\x05model\"\x13\n" +
	"\x11ListModelsRequest\"?\n" +
	"\x12ListModelsResponse\x12)\n" +
	"\x06models\x18\x01 \x03(\v2\x11.verdict.v1.ModelR\x06models\"\x8c\x01\n" +
	"\x0fEvaluateRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\vinputs_json\x18\x03 \x01(\tR\n" +
	"inputsJson\x12#\n" +
	"\rinclude_trace\x18\x04 \x01(\bR\fincludeTrace\"\xb5\x01\n" +
	"\x17EvaluateDecisionRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\vdecision_id\x18\x03 \x01(\tR\n" +
	"decisionId\x12\x1f\n" +
	"\vinputs_json\x18\x04 \x01(\tR\n" +
	"inputsJson\x12#\n" +
	"\rinclude_trace\x18\x05 \x01(\bR\fincludeTrace\"\xb2\x01\n" +
	"\x16EvaluateServiceRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\x12\x1f\n" +
	"\vinputs_json\x18\x04 \x01(\tR\n" +
	"inputsJson\x12#\n" +
	"\rinclude_trace\x18\x05 \x01(\bR\fincludeTrace\"\xca\x01\n" +
	"\x10EvaluateResponse\x12!\n" +
	"\foutputs_json\x18\x01 \x01(\tR\voutputsJson\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"trace_json\x18\x03 \x01(\tR\ttraceJson\x128\n" +
	"\vdiagnostics\x18\x04 \x03(\v2\x16.verdict.v1.DiagnosticR\vdiagnostics\x12\x1f\n" +
	"\vduration_ns\x18\x05 \x01(\x03R\n" +
	"durationNs\",\n" +
	"\x0fGetTraceRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\"1\n" +
	"\x10GetTraceResponse\x12\x1d\n" +
	"\n" +
	"trace_json\x18\x01 \x01(\tR\ttraceJson\"E\n" +
	"\x0eAnalyzeRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"l\n" +
	"\x0fAnalyzeResponse\x12\x1f\n" +
	"\vreport_json\x18\x01 \x01(\tR\n" +
	"reportJson\x128\n" +
	"\vdiagnostics\x18\x02 \x03(\v2\x16.verdict.v1.DiagnosticR\vdiagnostics\"f\n" +
	"\x0eExplainRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\vdecision_id\x18\x03 \x01(\tR\n" +
	"decisionId\"D\n" +
	"\x0fExplainResponse\x12\x1d\n" +
	"\n" +
	"slice_json\x18\x01 \x01(\tR\tsliceJson\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text*a\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x01\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x02\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x032\xe1\x04\n" +
	"\x06Engine\x12H\n" +
	"\tLoadModel\x12\x1c.verdict.v1.LoadModelRequest\x1a\x1d.verdict.v1.LoadModelResponse\x12K\n" +
	"\n" +
	"ListModels\x12\x1d.verdict.v1.ListModelsRequest\x1a\x1e.verdict.v1.ListModelsResponse\x12E\n" +
	"\bEvaluate\x12\x1b.verdict.v1.EvaluateRequest\x1a\x1c.verdict.v1.EvaluateResponse\x12U\n" +
	"\x10EvaluateDecision\x12#.verdict.v1.EvaluateDecisionRequest\x1a\x1c.verdict.v1.EvaluateResponse\x12S\n" +
	"\x0fEvaluateService\x12\".verdict.v1.EvaluateServiceRequest\x1a\x1c.verdict.v1.EvaluateResponse\x12E\n" +
	"\bGetTrace\x12\x1b.verdict.v1.GetTraceRequest\x1a\x1c.verdict.v1.GetTraceResponse\x12B\n" +
	"\aAnalyze\x12\x1a.verdict.v1.AnalyzeRequest\x1a\x1b.verdict.v1.AnalyzeResponse\x12B\n" +
	"\aExplain\x12\x1a.verdict.v1.ExplainRequest\x1a\x1b.verdict.v1.ExplainResponseB3Z1github.com/frankbardon/verdict/server/twirp;twirpb\x06proto3"

var (
	file_server_twirp_service_proto_rawDescOnce sync.Once
	file_server_twirp_service_proto_rawDescData []byte
)

func file_server_twirp_service_proto_rawDescGZIP() []byte {
	file_server_twirp_service_proto_rawDescOnce.Do(func() {
		file_server_twirp_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_twirp_service_proto_rawDesc), len(file_server_twirp_service_proto_rawDesc)))
	})
	return file_server_twirp_service_proto_rawDescData
}

var file_server_twirp_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_twirp_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_server_twirp_service_proto_goTypes = []any{
	(Severity)(0),                   // 0: verdict.v1.Severity
	(*Diagnostic)(nil),              // 1: verdict.v1.Diagnostic
	(*Model)(nil),                   // 2: verdict.v1.Model
	(*LoadModelRequest)(nil),        // 3: verdict.v1.LoadModelRequest
	(*LoadModelResponse)(nil),       // 4: verdict.v1.LoadModelResponse
	(*ListModelsRequest)(nil),       // 5: verdict.v1.ListModelsRequest
	(*ListModelsResponse)(nil),      // 6: verdict.v1.ListModelsResponse
	(*EvaluateRequest)(nil),         // 7: verdict.v1.EvaluateRequest
	(*EvaluateDecisionRequest)(nil), // 8: verdict.v1.EvaluateDecisionRequest
	(*EvaluateServiceRequest)(nil),  // 9: verdict.v1.EvaluateServiceRequest
	(*EvaluateResponse)(nil),        // 10: verdict.v1.EvaluateResponse
	(*GetTraceRequest)(nil),         // 11: verdict.v1.GetTraceRequest
	(*GetTraceResponse)(nil),        // 12: verdict.v1.GetTraceResponse
	(*AnalyzeRequest)(nil),          // 13: verdict.v1.AnalyzeRequest
	(*AnalyzeResponse)(nil),         // 14: verdict.v1.AnalyzeResponse
	(*ExplainRequest)(nil),          // 15: verdict.v1.ExplainRequest
	(*ExplainResponse)(nil),         // 16: verdict.v1.ExplainResponse
}
var file_server_twirp_service_proto_depIdxs = []int32{
	0,  // 0: verdict.v1.Diagnostic.severity:type_name -> verdict.v1.Severity
	1,  // 1: verdict.v1.Model.diagnostics:type_name -> verdict.v1.Diagnostic
	2,  // 2: verdict.v1.LoadModelResponse.model:type_name -> verdict.v1.Model
	2,  // 3: verdict.v1.ListModelsResponse.models:type_name -> verdict.v1.Model
	1,  // 4: verdict.v1.EvaluateResponse.diagnostics:type_name -> verdict.v1.Diagnostic
	1,  // 5: verdict.v1.AnalyzeResponse.diagnostics:type_name -> verdict.v1.Diagnostic
	3,  // 6: verdict.v1.Engine.LoadModel:input_type -> verdict.v1.LoadModelRequest
	5,  // 7: verdict.v1.Engine.ListModels:input_type -> verdict.v1.ListModelsRequest
	7,  // 8: verdict.v1.Engine.Evaluate:input_type -> verdict.v1.EvaluateRequest
	8,  // 9: verdict.v1.Engine.EvaluateDecision:input_type -> verdict.v1.EvaluateDecisionRequest
	9,  // 10: verdict.v1.Engine.EvaluateService:input_type -> verdict.v1.EvaluateServiceRequest
	11, // 11: verdict.v1.Engine.GetTrace:input_type -> verdict.v1.GetTraceRequest
	13, // 12: verdict.v1.Engine.Analyze:input_type -> verdict.v1.AnalyzeRequest
	15, // 13: verdict.v1.Engine.Explain:input_type -> verdict.v1.ExplainRequest
	4,  // 14: verdict.v1.Engine.LoadModel:output_type -> verdict.v1.LoadModelResponse
	6,  // 15: verdict.v1.Engine.ListModels:output_type -> verdict.v1.ListModelsResponse
	10, // 16: verdict.v1.Engine.Evaluate:output_type -> verdict.v1.EvaluateResponse
	10, // 17: verdict.v1.Engine.EvaluateDecision:output_type -> verdict.v1.EvaluateResponse
	10, // 18: verdict.v1.Engine.EvaluateService:output_type -> verdict.v1.EvaluateResponse
	12, // 19: verdict.v1.Engine.GetTrace:output_type -> verdict.v1.GetTraceResponse
	14, // 20: verdict.v1.Engine.Analyze:output_type -> verdict.v1.AnalyzeResponse
	16, // 21: verdict.v1.Engine.Explain:output_type -> verdict.v1.ExplainResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_server_twirp_service_proto_init() }
func file_server_twirp_service_proto_init() {
	if File_server_twirp_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_twirp_service_proto_rawDesc), len(file_server_twirp_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_twirp_service_proto_goTypes,
		DependencyIndexes: file_server_twirp_service_proto_depIdxs,
		EnumInfos:         file_server_twirp_service_proto_enumTypes,
		MessageInfos:      file_server_twirp_service_proto_msgTypes,
	}.Build()
	File_server_twirp_service_proto = out.File
	file_server_twirp_service_proto_goTypes = nil
	file_server_twirp_service_proto_depIdxs = nil
}
