"""Splice generated diagram interchange into the hand-authored examples.

The examples are hand-written because their comments are the documentation.
Their DMNDI is generated, because coordinates are not something a human should
maintain: run this again after changing a model's shape and the diagram follows.
"""
import re
import subprocess
import sys

DECLS = (
    '             xmlns:dmndi="https://www.omg.org/spec/DMN/20191111/DMNDI/"\n'
    '             xmlns:dc="http://www.omg.org/spec/DMN/20180521/DC/"\n'
    '             xmlns:di="http://www.omg.org/spec/DMN/20180521/DI/"\n'
)

for path in sys.argv[1:]:
    generated = subprocess.run(
        ["bin/verdict", "convert", path, "--to", "xml"],
        capture_output=True, text=True, check=True).stdout

    m = re.search(r'[ ]*<dmndi:DMNDI>.*?</dmndi:DMNDI>\n', generated, re.S)
    if not m:
        print("no diagram generated for", path)
        continue
    diagram = m.group(0)

    s = open(path, encoding='utf-8').read()
    s = re.sub(r'[ ]*<dmndi:DMNDI>.*?</dmndi:DMNDI>\n', '', s, flags=re.S)

    if 'xmlns:dmndi' not in s:
        s = re.sub(r'(<definitions xmlns="[^"]*"\n)', r'\1' + DECLS, s, count=1)

    marker = '\n</definitions>'
    assert marker in s, path
    s = s.replace(
        marker,
        '\n  <!-- Diagram interchange, generated by `verdict convert` and spliced in\n'
        '       by scripts/add-diagram.py. dmn-js has nothing to draw without it, so a\n'
        '       model with no DMNDI opens as an empty canvas in Camunda Modeler. -->\n'
        + diagram.rstrip('\n') + marker)
    open(path, 'w', encoding='utf-8').write(s)
    print("added diagram to", path)
